name: 'Feature Request'
description: Suggest a feature for Heavy Duty Framework

body:
    - type: dropdown
      id: affected-packages
      attributes:
          label: Which @nhhockeyplayer/* package(s) are relevant/related to the feature request?
          options:
              - meanstacknh
              - admin
              - shared-ui-widgets
              - Don't known / other
          multiple: true

    - type: textarea
      id: description
      attributes:
          label: Description
      validations:
          required: true

    - type: textarea
      id: proposed-solution
      attributes:
          label: Proposed solution
      validations:
          required: true

    - type: textarea
      id: alternatives-considered
      attributes:
          label: Alternatives considered
      validations:
          required: true
